#!/usr/bin/env python3

import psutil
from sys import argv

def main():
    
    errmsg = ('Use command with parameter: \ncpu - CPU Metrics; \nmem - Memory Metrics.')
    try:
        param = argv[1]
        if param == 'cpu':
        
            metrics = psutil.cpu_times()
            sum = 0
            for i in metrics:
                sum = sum + i
            
            cpuIdle = metrics.idle * 100 / sum
            system = "system.cpu.idle " + str("%.2f" % cpuIdle)
            print(system)
            
            cpuUser = metrics.user * 100 / sum
            system = "system.cpu.user " + str("%.2f" % cpuUser)
            print(system)
            
            cpuGuest = metrics.guest * 100 / sum
            system = "system.cpu.guest " + str("%.2f" % cpuGuest)
            print(system)
            
            cpuIowait = metrics.iowait * 100 / sum
            system = "system.cpu.iowait " + str("%.2f" %cpuIowait)
            print(system)
            
            cpuStolen = metrics.steal * 100 / sum
            system = "system.cpu.stolen " + str("%.2f" % cpuStolen)
            print(system)
            
            cpuSystem = metrics.system * 100 / sum
            system = "system.cpu.system  " + str("%.2f" % cpuSystem)
            print(system)
        elif param == 'mem':
            metrics = psutil.virtual_memory()
            
            virtualTotal = metrics.total
            system = "virtual total " + str("%.f" % virtualTotal)
            print(system)
            
            virtualUsed = metrics.used
            system = "virtual used " + str("%.f" % virtualUsed)
            print(system)
            
            virtualFree = metrics.free
            system = "virtual free " + str("%.f" % virtualFree)
            print(system)
            
            virtualShared = metrics.shared
            system = "virtual shared " + str("%.f" % virtualShared)
            print(system)
            
            metricsswap = psutil.swap_memory()
            
            swapTotal = metricsswap.total
            system = "swap total " + str("%.f" % swapTotal)
            print(system)
            
            swapUsed = metricsswap.used
            system = "swap used " + str("%.f" % swapUsed)
            print(system)
            
            swapFree = metricsswap.free
            system = "swap free " + str("%.f" % swapFree)
            print(system)
            
        else:
            print ('Error!' + ' ' + errmsg)
        
    except IndexError:
        print ('Use command with parameter: \ncpu - CPU Metrics; \nmem - Memory Metrics.')
    
main()
