#!/usr/bin/env python3

import psutil
from sys import argv

def main():
    result = True
    errmsg = ('Use command with parameter: \ncpu - CPU Metrics; \nmem - Memory Metrics.')

    try:
        param = argv[1]

        if param == 'cpu':
            metrics = psutil.cpu_times()
        elif param == 'mem':
            metrics = psutil.virtual_memory()
        else:
            print ('Error!' + ' ' + errmsg)
            result = False
        if result:
            for k,v in metrics._asdict().items():
                print (k + ' ' + str(v))
    except IndexError:
	    print ('Use command with parameter: \ncpu - CPU Metrics; \nmem - Memory Metrics.')

main()